In [14]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(threshold=np.nan)
import pandas as pd
import string

In [15]:
# Read the csv file into a pandas DataFrame

data = pd.read_csv('df_key_players_3.csv')
data.head()

From  CEO - David Delainey  CEO - Jeff Skilling  \
0     CEO - David Delainey                   NaN                 34.0   
1      CEO - Jeff Skilling                   3.0                  NaN   
2      CEO - John Lavorato                 148.0                  NaN   
3  Director - Andrew Lewis                   NaN                  NaN   
4  Director - Geoff Storey                   NaN                  NaN   

   CEO - John Lavorato  CEO - Kenneth Lay  Director - Andrew Lewis  \
0                164.0               28.0                      NaN   
1                  NaN                NaN                      NaN   
2                  NaN                9.0                      NaN   
3                  NaN                NaN                      NaN   
4                  NaN                NaN                      NaN   

   Director - Geoff Storey  Director - Jonathan Mckay  Director - Keith Holst  \
0                      NaN                        NaN                     NaN   
1                      NaN                        NaN                     NaN   
2                      NaN                       25.0                     NaN   
3                      NaN                        NaN                     NaN   
4                      NaN                        NaN                     1.0   

   Director - Kevin Hyatt               ...                \
0                     NaN               ...                 
1                     NaN               ...                 
2                     NaN               ...                 
3                     NaN               ...                 
4                     NaN               ...                 

   Vice President - Joe Stepenovitch  Vice President - John Arnold  \
0                                NaN                           NaN   
1                                NaN                           NaN   
2                                NaN                         117.0   
3                                NaN                           NaN   
4                                NaN                           NaN   

   Vice President - Kevin Presto  Vice President - Richard Sanders  \
0                           43.0                               4.0   
1                            NaN                               NaN   
2                           77.0                               NaN   
3                            NaN                               NaN   
4                            NaN                               NaN   

   Vice President - Richard Shapiro  Vice President - Rod Hayslett  \
0                              10.0                            NaN   
1                               NaN                            1.0   
2                              13.0                            NaN   
3                               NaN                            NaN   
4                               NaN                            NaN   

   Vice President - Scott Neal  Vice President - Shelley Corman  \
0                          NaN                              NaN   
1                          NaN                              NaN   
2                          7.0                              NaN   
3                          NaN                              NaN   
4                          NaN                              NaN   

   Vice President - Steven Kean  Vice President - Thomas Martin  
0                          30.0                             NaN  
1                           NaN                             NaN  
2                           NaN                             4.0  
3                           NaN                             NaN  
4                           NaN                             NaN  

[5 rows x 49 columns]

In [16]:
data = data.fillna(0)
data.head()

From  CEO - David Delainey  CEO - Jeff Skilling  \
0     CEO - David Delainey                   0.0                 34.0   
1      CEO - Jeff Skilling                   3.0                  0.0   
2      CEO - John Lavorato                 148.0                  0.0   
3  Director - Andrew Lewis                   0.0                  0.0   
4  Director - Geoff Storey                   0.0                  0.0   

   CEO - John Lavorato  CEO - Kenneth Lay  Director - Andrew Lewis  \
0                164.0               28.0                      0.0   
1                  0.0                0.0                      0.0   
2                  0.0                9.0                      0.0   
3                  0.0                0.0                      0.0   
4                  0.0                0.0                      0.0   

   Director - Geoff Storey  Director - Jonathan Mckay  Director - Keith Holst  \
0                      0.0                        0.0                     0.0   
1                      0.0                        0.0                     0.0   
2                      0.0                       25.0                     0.0   
3                      0.0                        0.0                     0.0   
4                      0.0                        0.0                     1.0   

   Director - Kevin Hyatt               ...                \
0                     0.0               ...                 
1                     0.0               ...                 
2                     0.0               ...                 
3                     0.0               ...                 
4                     0.0               ...                 

   Vice President - Joe Stepenovitch  Vice President - John Arnold  \
0                                0.0                           0.0   
1                                0.0                           0.0   
2                                0.0                         117.0   
3                                0.0                           0.0   
4                                0.0                           0.0   

   Vice President - Kevin Presto  Vice President - Richard Sanders  \
0                           43.0                               4.0   
1                            0.0                               0.0   
2                           77.0                               0.0   
3                            0.0                               0.0   
4                            0.0                               0.0   

   Vice President - Richard Shapiro  Vice President - Rod Hayslett  \
0                              10.0                            0.0   
1                               0.0                            1.0   
2                              13.0                            0.0   
3                               0.0                            0.0   
4                               0.0                            0.0   

   Vice President - Scott Neal  Vice President - Shelley Corman  \
0                          0.0                              0.0   
1                          0.0                              0.0   
2                          7.0                              0.0   
3                          0.0                              0.0   
4                          0.0                              0.0   

   Vice President - Steven Kean  Vice President - Thomas Martin  
0                          30.0                             0.0  
1                           0.0                             0.0  
2                           0.0                             4.0  
3                           0.0                             0.0  
4                           0.0                             0.0  

[5 rows x 49 columns]

In [33]:
drop_from= data.drop(columns= 'From')
drop_from

CEO - David Delainey  CEO - Jeff Skilling  CEO - John Lavorato  \
0                    0.0                 34.0                164.0   
1                    3.0                  0.0                  0.0   
2                  148.0                  0.0                  0.0   
3                    0.0                  0.0                  0.0   
4                    0.0                  0.0                  0.0   
5                    0.0                  0.0                 29.0   
6                    0.0                  0.0                  6.0   
7                    1.0                  0.0                  0.0   
8                    0.0                  0.0                  0.0   
9                    0.0                  0.0                  0.0   
10                   0.0                  0.0                  0.0   
11                   0.0                  0.0                  1.0   
12                   4.0                  0.0                  0.0   
13                   0.0                  0.0                  0.0   
14                   0.0                  0.0                  0.0   
15                   0.0                  5.0                  0.0   
16                   0.0                  0.0                  0.0   
17                   0.0                  0.0                  0.0   
18                   0.0                  0.0                  0.0   
19                   0.0                  0.0                  0.0   
20                   4.0                  0.0                  5.0   
21                   0.0                  0.0                  0.0   
22                   0.0                  0.0                  0.0   
23                   0.0                  0.0                  0.0   
24                   0.0                  0.0                  0.0   
25                   0.0                  0.0                  0.0   
26                   0.0                  0.0                  8.0   
27                   4.0                  0.0                 11.0   
28                   0.0                  0.0                  0.0   
29                   4.0                  0.0                 16.0   
30                   0.0                  0.0                  1.0   
31                   0.0                  0.0                 33.0   
32                  26.0                  0.0                  7.0   
33                   0.0                  0.0                  0.0   
34                   0.0                  0.0                  0.0   
35                   0.0                  0.0                162.0   
36                   0.0                  0.0                 42.0   
37                   6.0                  0.0                  0.0   
38                  12.0                  0.0                 19.0   
39                   0.0                  1.0                  0.0   
40                   7.0                  0.0                 25.0   
41                   0.0                  0.0                  0.0   
42                  23.0                 35.0                  5.0   
43                   0.0                  0.0                  4.0   

    CEO - Kenneth Lay  Director - Andrew Lewis  Director - Geoff Storey  \
0                28.0                      0.0                      0.0   
1                 0.0                      0.0                      0.0   
2                 9.0                      0.0                      0.0   
3                 0.0                      0.0                      0.0   
4                 0.0                      0.0                      0.0   
5                 0.0                      0.0                      0.0   
6                 0.0                      0.0                      1.0   
7                 2.0                      0.0                      0.0   
8                 0.0                      0.0                      0.0   
9                 0.0                      0.0                      0.0   
10                0.0       

In [18]:
df = drop_from.values
df

array([[  0.,  34., 164.,  28.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   3.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,
          0.,   7.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,
          0.,   0.,   4.,  61.,   0.,   0.,   0.,  43.,   4.,  10.,   0.,
          0.,   0.,  30.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          0.,   0.,   0.,   0.],
       [148.,   0.,   0.,   9.,   0.,   0.,  25.,   0.,   0.,   0.,   1.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   6.,   0.,   0.,   0.,   1.,   0.,   8.,  23.,  22.,   0.,
          7.,   0.,   7.,   6.,   0.,   0., 117.,  77.,   0.,  13.,   0.,
          7.,   0.,   0.,   4.],
       [  0.,

In [19]:
df =  list(df)

In [20]:
df

[array([  0.,  34., 164.,  28.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   3.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,
          0.,   7.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,   0.,
          0.,   0.,   4.,  61.,   0.,   0.,   0.,  43.,   4.,  10.,   0.,
          0.,   0.,  30.,   0.]),
 array([3., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
 array([148.,   0.,   0.,   9.,   0.,   0.,  25.,   0.,   0.,   0.,   1.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   6.,   0.,   0.,   0.,   1.,   0.,   8.,  23.,  22.,   0.,
          7.,   0.,   7.,   6.,   0.,   0., 117.,  77.,   0.,  13.,   0.,
          7.,   0.,   0.,   4.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [26]:
df = pd.DataFrame(df)
df.head()

0     1      2     3    4    5     6    7    8    9  ...    38     39  \
0    0.0  34.0  164.0  28.0  0.0  0.0   0.0  0.0  0.0  0.0 ...   0.0    0.0   
1    3.0   0.0    0.0   0.0  0.0  0.0   0.0  0.0  0.0  0.0 ...   0.0    0.0   
2  148.0   0.0    0.0   9.0  0.0  0.0  25.0  0.0  0.0  0.0 ...   0.0  117.0   
3    0.0   0.0    0.0   0.0  0.0  0.0   0.0  0.0  0.0  0.0 ...   0.0    0.0   
4    0.0   0.0    0.0   0.0  0.0  0.0   0.0  1.0  0.0  0.0 ...   0.0    0.0   

     40   41    42   43   44   45    46   47  
0  43.0  4.0  10.0  0.0  0.0  0.0  30.0  0.0  
1   0.0  0.0   0.0  1.0  0.0  0.0   0.0  0.0  
2  77.0  0.0  13.0  0.0  7.0  0.0   0.0  4.0  
3   0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0  
4   0.0  0.0   0.0  0.0  0.0  0.0   0.0  0.0  

[5 rows x 48 columns]

In [28]:
df = df.astype(int)

In [30]:
df.head()

0   1    2   3   4   5   6   7   8   9  ...  38   39  40  41  42  43  44  \
0    0  34  164  28   0   0   0   0   0   0 ...   0    0  43   4  10   0   0   
1    3   0    0   0   0   0   0   0   0   0 ...   0    0   0   0   0   1   0   
2  148   0    0   9   0   0  25   0   0   0 ...   0  117  77   0  13   0   7   
3    0   0    0   0   0   0   0   0   0   0 ...   0    0   0   0   0   0   0   
4    0   0    0   0   0   0   0   1   0   0 ...   0    0   0   0   0   0   0   

   45  46  47  
0   0  30   0  
1   0   0   0  
2   0   0   4  
3   0   0   0  
4   0   0   0  

[5 rows x 48 columns]

In [31]:
df.values

array([[  0,  34, 164,  28,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   3,   0,   0,   3,   0,   0,   0,   0,   0,   7,   0,   0,
          0,   0,   0,   0,   0,  15,   0,   0,   0,   4,  61,   0,   0,
          0,  43,   4,  10,   0,   0,   0,  30,   0],
       [  3,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   1,   0,   0,   0,   0],
       [148,   0,   0,   9,   0,   0,  25,   0,   0,   0,   1,   0,   0,
          1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0,   0,
          0,   1,   0,   8,  23,  22,   0,   7,   0,   7,   6,   0,   0,
        117,  77,   0,  13,   0,   7,   0,   0,   4],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   